### ISSUE TITLE
Error when trying to save an update -Nothing is saved, or PS Error: Invoke-WebRequest : Cannot convert 'System.String[]' to the type 'System.Uri' required by parameter 'Uri'. Specified method is not supported.

### ISSUE THREAD

**Issue by joshuabengal** [potatoqualitee/kbupdate#141]
Fresh Windows 7 install. Updated Powershell to 5.1. Installed NuGet and kbupdate. All good. 

When I run a command to download a hotfix, either nothing is downloaded, or I get an error

1. I enter "Save-KbUpdate -Name KB2849697 -Path C:\HOTFIX", it runs, I see the green pop up, I get no error, but nothing is saved. 

2. I tried an example from the wiki, Save-KbUpdate -Name KB4057119, and I get the error
"Invoke-WebRequest : Cannot convert 'System.String[]' to the type 'System.Uri' required by parameter 'Uri'. Specified
method is not supported."

I tried some other KB #'s, and nothing works. Some seem to trigger multiple downloads, but all the downloads fail with the same error as I get in example #2 

Any ideas on what to try next?

**Comment by potatoqualitee** [comment]
thanks! I can repro. let me fix this

**Comment by potatoqualitee** [comment]
ahh 

1. this patch does not exist in the catalog

https://www.catalog.update.microsoft.com/Search.aspx?q=KB2849697

2. this actually works for me :/ 


can you update to the latest version?

`Save-KbUpdate -Name KB4057119 -Path C:\temp\bug` saved two files for me

**Comment by joshuabengal** [comment]
I ran the `systeminfo` command on my PC, and the first hotfix listed is [01]: KB2849697. Odd that it is not showing up on the search but but is installed on my system? Any idea how that could happen? 

I just re-ran `Install-Module kbupdate -Scope CurrentUser` command in powershell and then ran Save-KbUpdate -Name KB4057119 -Path C:\hotfix and it worked. 

I tried KB2849696, which is the second hotfix listed on my `systeminfo`, and again it found nothing. I tried the third item on my list, however, and that did work and downloaded. 

Any thoughts on how to get a hotfix that was downloaded and installed but not showing up in the tool?

**Comment by potatoqualitee** [comment]
ive seen that before, pretty often actually, and have no idea :/

**Comment by tayzer522** [comment]
I'm seeing this same issue as above in example 2.
Here is the full error output:
Invoke-WebRequest : Cannot convert 'System.String[]' to the type 'System.Uri' required by parameter 'Uri'. Specified method is not supported.
At line:33 char:27
+         Invoke-WebRequest @Args -WebSession $script:websession -UseBa ...
+                           ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgument,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by potatoqualitee** [comment]
@tayzer522 please update to the latest version

**Comment by tayzer522** [comment]
I am on the latest version (1.5.2) and still seeing this issue.

**Comment by potatoqualitee** [comment]
I'm trying to repro and cannot

It's the second example, right? I am able to download with no issue. Can you close your PS, reopen, then `Import-Module kbupdate -RequiredVersion 1.5.2`

```
[0s] C:/github❯ Import-Module kbupdate -RequiredVersion 1.5.2
[5s] C:/github❯ Save-KbUpdate -Pattern MS15-101                                                                                                                                                                                                                             
    Directory: C:\github


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        8/20/2015  12:59 AM         301424   windows8-rt-kb3074231-x64_2a21c3e86102268c78e4db8c7a986cadf9288e4f.msu
```

Let me know what happens? Thanks

**Comment by tayzer522** [comment]
Still receiving the same error, even after re-importing the module.

**Comment by tayzer522** [comment]
Name                           Value                                                                                                                                                 
----                           -----                                                                                                                                                 
PSVersion                      5.1.19041.1682                                                                                                                                        
PSEdition                      Desktop                                                                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                               
BuildVersion                   10.0.19041.1682                                                                                                                                       
CLRVersion                     4.0.30319.42000                                                                                                                                       
WSManStackVersion              3.0                                                                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                                                                   
SerializationVersion           1.1.0.1                                                                                                                                               

Name              : kbupdate
Path              : C:\Users\[REDACTED]\Documents\WindowsPowerShell\Modules\kbupdate\1.5.2\kbupdate.psm1
Description       : KB Viewer, Saver, Installer and Uninstaller
Guid              : f292e190-ed32-4232-b9f3-b50b42a5655f
Version           : 1.5.2
ModuleBase        : C:\Users\[REDACTED]\Documents\WindowsPowerShell\Modules\kbupdate\1.5.2
ModuleType        : Script
PrivateData       : {PSData}
AccessMode        : ReadWrite
ExportedAliases   : {}
ExportedCmdlets   : {}
ExportedFunctions : {[Connect-KbWsusServer, Connect-KbWsusServer], [Get-KbInstalledUpdate, Get-KbInstalledUpdate], [Get-KbUpdate, Get-KbUpdate], [Get-KbWSUSSCNFile, 
                    Get-KbWSUSSCNFile]...}
ExportedVariables : {}
NestedModules     : {kbupdate-library}


Path : C:\Users\[REDACTED]\Documents\WindowsPowerShell\Modules\kbupdate\1.5.2\kbupdate.psm1


PSMessageDetails      : 
Exception             : System.Runtime.InteropServices.COMException (0x800704DD): The operation being requested was not performed because the user has not logged on to the network. 
                        The specified service does not exist. (Exception from HRESULT: 0x800704DD)
                           at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
                           at Microsoft.BackgroundIntelligentTransfer.Management.Interop.Job.Cancel()
                           at Microsoft.BackgroundIntelligentTransfer.Management.NewBitsTransferCommand.ProcessRecord()
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Start-BitsTransfer], COMException
FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.BackgroundIntelligentTransfer.Management.NewBitsTransferCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Save-KbUpdate<Process>, <No file>: line 283
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

**Comment by potatoqualitee** [comment]
Ohhh interesting! 

```
The operation being requested was not performed because the user has not logged on to the network.
```

Are you saving to a file share? If so, can you save to a local disk instead? If not, maybe `Start-BitsTransfer` is messing up. Are you behind a proxy?

Can you run this to the destination that you're saving and let me know what you see

```
Start-BitsTransfer -Source https://catalog.s.download.windowsupdate.com/c/msdownload/update/software/secu/2022/06/sqlserver2016-kb5014365-x64_147f6446eb6bce80fcb819b8cced77dec95ea12a.exe -Destination whatever
```

can you play with Start-BitsTransfer until it works? Can you check if bits is running?

```
Get-Service bits
```

**Comment by tayzer522** [comment]
I'm trying to save locally, and BITS is running. I've even tried restarting the service. This is what I get with the bits transfer:
`Start-BitsTransfer : The operation being requested was not performed because the user has not logged on to the network. The specified service does not exist. (Exception from 
HRESULT: 0x800704DD)
At line:1 char:1
+ Start-BitsTransfer -Source https://catalog.s.download.windowsupdate.c ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-BitsTransfer], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.BackgroundIntelligentTransfer.Management.NewBitsTransferCommand`

**Comment by tayzer522** [comment]
I apologize, the deeper I look into it, the more it appears it has to do with my machine/network. Something to do with permissions and running with different accounts. Not sure what's changed as it used to work great. Sorry for wasting your time :(

**Comment by potatoqualitee** [comment]
No problem! It's not a waste. What I can do is add in resiliency to use a different method if Start-BitsTransfer fails. Are you running the command as admin? Seems bits doesnt like that.

**Comment by tayzer522** [comment]
Yes, running Powershell as admin.

**Comment by potatoqualitee** [comment]
seems like that may be the issue. but i'll address a failback in a future release 👍🏼

**Comment by potatoqualitee** [comment]
AH HA! The failback used a variable `$link` which is set as an array in the parameters. Thanks for reporting this, it'll be fixed in the next release.
